class BotError(Exception):
    """Исключения обработаные Ботом."""

    pass
